import { ConvexError } from "convex/values";

/**
 * S22 upload transport: POSTs the file bytes to the authenticated S08
 * `/private-uploads` HTTP action. The response is status metadata only, so
 * there is never a storage id or bearer URL for the browser to leak, and every
 * failure resolves to a typed Convex error code the UI maps to fixed copy.
 * The idempotency key is generated by the caller and stays stable for one
 * selected file, so a retried upload cannot create a second document.
 */

/** Mirrors the server's extension allowlist; the server revalidates all of it. */
export const UPLOAD_CONTENT_TYPES: Record<string, string> = {
  pdf: "application/pdf",
  md: "text/markdown",
  markdown: "text/markdown",
  txt: "text/plain",
};

export function uploadExtension(filename: string): string | null {
  const dot = filename.lastIndexOf(".");
  if (dot <= 0 || dot === filename.length - 1) return null;
  return filename.slice(dot + 1).toLowerCase();
}

/** The content type the S08 action requires for this filename, or null. */
export function uploadContentType(filename: string): string | null {
  const extension = uploadExtension(filename);
  if (extension === null) return null;
  return UPLOAD_CONTENT_TYPES[extension] ?? null;
}

export function buildUploadUrl(siteUrl: string, params: { projectId: string; filename: string; idempotencyKey: string }): string {
  const query = new URLSearchParams({ projectId: params.projectId, filename: params.filename, idempotencyKey: params.idempotencyKey });
  return `${siteUrl.replace(/\/+$/, "")}/private-uploads?${query.toString()}`;
}

export type UploadBody = { documentId: string; jobId: string; filename: string; status: string; idempotent: boolean };

function fail(code: string): never {
  throw new ConvexError({ code });
}

/**
 * Pure status/body mapping: 200 (idempotent replay) and 201 (fresh commit)
 * both carry the same metadata shape; anything else surfaces its typed code.
 */
export function mapUploadResponse(status: number, body: unknown): UploadBody {
  const record = typeof body === "object" && body !== null ? (body as Record<string, unknown>) : null;
  if (status === 200 || status === 201) {
    if (record === null || typeof record.documentId !== "string" || typeof record.jobId !== "string" || typeof record.filename !== "string") {
      fail("UPLOAD_FAILED");
    }
    const statusValue = typeof record.status === "string" ? record.status : "pending";
    return { documentId: record.documentId, jobId: record.jobId, filename: record.filename, status: statusValue, idempotent: status === 200 };
  }
  const code = record !== null && typeof record.code === "string" ? record.code : null;
  if (code !== null) fail(code);
  if (status === 401) fail("UNAUTHENTICATED");
  if (status === 404) fail("NOT_FOUND");
  if (status === 413) fail("FILE_TOO_LARGE");
  if (status === 415) fail("UNSUPPORTED_MEDIA_TYPE");
  if (status === 507) fail("QUOTA_EXCEEDED");
  fail("UPLOAD_FAILED");
}

export type UploadRequest = {
  siteUrl: string;
  token: string | null;
  projectId: string;
  filename: string;
  idempotencyKey: string;
  bytes: Blob;
  fetchImpl?: (input: string, init?: RequestInit) => Promise<Response>;
};

/**
 * Sends one file to the authenticated upload action. A missing token or an
 * unsupported media type fails before any byte leaves the browser, and a
 * dropped connection becomes a typed NETWORK error instead of a thrown string.
 */
export async function requestDocumentUpload(request: UploadRequest): Promise<UploadBody> {
  if (request.token === null || request.token === "") fail("UNAUTHENTICATED");
  const contentType = uploadContentType(request.filename);
  if (contentType === null) fail("UNSUPPORTED_MEDIA_TYPE");
  const fetchImpl = request.fetchImpl ?? ((input: string, init?: RequestInit) => fetch(input, init));
  let response: Response;
  let payload: Uint8Array<ArrayBuffer>;
  try {
    // A plain byte view is what every runtime accepts as a request body (the
    // jsdom test environment's Blob shim is not).
    payload = new Uint8Array(await request.bytes.arrayBuffer());
  } catch {
    fail("NETWORK");
  }
  try {
    response = await fetchImpl(buildUploadUrl(request.siteUrl, request), {
      method: "POST",
      headers: { authorization: `Bearer ${request.token}`, "content-type": contentType },
      body: payload,
    });
  } catch {
    fail("NETWORK");
  }
  let body: unknown = null;
  try {
    body = await response.json();
  } catch {
    body = null;
  }
  return mapUploadResponse(response.status, body);
}

/** Stable per-selection idempotency key: retries of the same file reuse it. */
export function newUploadIdempotencyKey(): string {
  if (typeof crypto !== "undefined" && "randomUUID" in crypto) return crypto.randomUUID();
  return `upload-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 12)}`;
}
